# Generated by Django 2.0 on 2018-10-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chooses_Date_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('chooses_date', models.DateField(blank=True, verbose_name='Chooses date')),
            ],
            options={
                'verbose_name': 'Chooses date',
                'verbose_name_plural': 'Chooses date',
            },
        ),
        migrations.CreateModel(
            name='Task_Details_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Task title')),
                ('date_of_task_execution', models.DateField(verbose_name='Date of task execution')),
                ('status', models.CharField(blank=True, default='In the process', max_length=20, verbose_name='Status of task')),
                ('content', models.CharField(max_length=50, verbose_name='Task description')),
                ('task_created_on', models.DateField(auto_now_add=True, verbose_name='Date of add task')),
            ],
            options={
                'verbose_name': 'Task description',
                'verbose_name_plural': 'Task description',
            },
        ),
    ]
