# Generated by Django 2.0 on 2018-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_task_details_model_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooses_date_model',
            name='chooses_date',
            field=models.DateField(verbose_name='Chooses date'),
        ),
    ]
