# Generated by Django 2.0 on 2018-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20181019_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_details_model',
            old_name='author',
            new_name='who_execute',
        ),
        migrations.RemoveField(
            model_name='chooses_date_model',
            name='name',
        ),
        migrations.AddField(
            model_name='task_details_model',
            name='from_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='From whom task shared'),
        ),
    ]
