# Generated by Django 2.0 on 2018-10-22 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_auto_20181022_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_details_model',
            name='from_user',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, verbose_name='From whom task shared'),
            preserve_default=False,
        ),
    ]
