# Generated by Django 2.0 on 2018-10-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_auto_20181022_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chooses_Date_Model',
        ),
        migrations.AlterField(
            model_name='task_details_model',
            name='who_execute',
            field=models.CharField(max_length=50, verbose_name='Who execute the task'),
        ),
    ]
